steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/fastapi-your-data:latest",
        "./backend",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/fastapi-your-data:latest"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "cloudrun-service" # Make sure this is your service name
      - "--image=gcr.io/$PROJECT_ID/fastapi-your-data:latest"
      - "--region=us-central1" # Confirm this is your desired region
      - "--platform=managed"
      - "--allow-unauthenticated" # Consider removing if you need authenticatio

images:
  - "gcr.io/$PROJECT_ID/fastapi-your-data:latest"
