"""Initial migration

Revision ID: f9d4e03034e4
Revises: 
Create Date: 2024-01-09 15:03:58.527757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9d4e03034e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_downloads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_downloads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('download_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('downloaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('keywords_namefile', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
