"""Edit columns companies

Revision ID: 734b2b1ea3a7
Revises: 3813a9d96f3f
Create Date: 2024-01-25 12:29:33.280074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734b2b1ea3a7'
down_revision = '3813a9d96f3f'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
