"""Edit columns companies

Revision ID: 98924ad486ab
Revises: 53738c6ef326
Create Date: 2024-01-25 12:24:28.353053

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '98924ad486ab'
down_revision = '53738c6ef326'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('companies', 'founded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('founded', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'notes')
    # ### end Alembic commands ###
