"""Edit columns companies

Revision ID: 98b54a9235d3
Revises: 734b2b1ea3a7
Create Date: 2024-01-28 16:38:20.489174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b54a9235d3'
down_revision = '734b2b1ea3a7'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
